Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-18.04"
    # не проверять репозиторий на наличие обновлений
    config.vm.box_check_update = false

    config.vm.network "forwarded_port", guest: 5000, host: 50561

    # отменить создание ssh-ключа
    config.ssh.insert_key = false
    config.vm.provider "virtualbox" do |vb|
    # имя виртуальной машины
    vb.name = "ubuntu-18-04"
    # объем оперативной памяти
    vb.memory = 2048
    # количество ядер процессора
    vb.cpus = 1
    end
    
    # hostname виртуальной машины
    config.vm.hostname = "ubuntu-18-04"
    
    config.vm.provision "shell", inline: "wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb"
    config.vm.provision "shell", inline: "sudo dpkg -i packages-microsoft-prod.deb"
    config.vm.provision "shell", inline: "rm packages-microsoft-prod.deb"
    config.vm.provision "shell", inline: "sudo apt-get update"
    config.vm.provision "shell", inline: "sudo apt-get install -y apt-transport-https"
    config.vm.provision "shell", inline: "sudo apt-get update"
    config.vm.provision "shell", inline: "sudo apt-get install -y dotnet-sdk-5.0"

    config.vm.provision "shell", inline: "sudo rm -rf /var/lab5"
    config.vm.provision "shell", inline: "sudo mkdir -p /var/lab5"
    config.vm.provision "shell", inline: "sudo chmod ugo+rwx /var/lab5"
    config.vm.provision "file", source: "../../CrossPlatformLab5/bin/Release/net5.0/publish", destination: "/var/lab5"
    config.vm.provision "shell", path: "startup.sh"
end